### ISSUE TITLE
Cant run the example 

### ISSUE THREAD

**Issue by germayneng** [ing-bank/popmon#131]
I install with a fresh environment - python 3.7 and ran any of the examples but I have the following error when generating reports:

```
$ conda create -n pop python=3.7
$ conda activate pop
$ pip install popmon
```

```
TypeError: isinstance() arg 2 must be a type or tuple of types
```

**Comment by sbrugman** [comment]
Thanks for reporting. One of our dependencies was failing with python 3.7 and our tests didn't catch that since they were running on 3.6. In the 0.4.1 release the issue should be resolved, and the CI/CD now also covers later versions of python.
