### ISSUE TITLE
Error when stitching histograms

### ISSUE THREAD

**Issue by mbaak** [ing-bank/popmon#143]
### Discussed in https://github.com/ing-bank/popmon/discussions/142

<div type='discussions-op-text'>

<sup>Originally posted by **jeaninejuliettes** September 29, 2021</sup>
Hello,

I'm receiving an error when using stitch_histogram and I'm not sure what I'm doing wrong, hope anyone can help me. The error I get is: **ValueError: Request to insert delta hists but time_bin_idx not set. Please do.**

The steps I take:

#### I start with creating a histogrammar object of the original dataframe
hists = df.pm_make_histograms()
bin_specs = popmon.get_bin_specs(hists)

#### later on I receive a new batch of data, which I add to my existing histograms
new_hists = [new_df.pm_make_histograms(bin_specs=bin_specs)]
hists_2= popmon.stitch_histograms(hists_basis=hists, hists_delta=new_hists, time_axis="batch")

#### so far so good, but when I try to repeat these steps with yet another new batch of data, I receive the error
new_hists_2 = [new_df_2.pm_make_histograms(bin_specs=bin_specs)]
hists_3 = popmon.stitch_histograms(hists_basis=hists_2, hists_delta=new_hists_2, time_axis="batch")

Is it not possible to stitch another histogram again? If not, I've found a bit of a cumbersome way to decide on what a good value for my time_bin_idx is. It works so far, but I'm expecting it too fail with other data (or not to work as expected). The way I define the time_bin_idx value is: 
int(np.ceil(max(hists_2[next(iter(hists_2))].bin_centers()) + 1))

Hopefully you can point me in the right direction. Thanks! 
</div>

**Comment by mbaak** [comment]
I've tried to, but I'm afraid I cannot reproduce your problem. In my setup the stitching of multiple batches works okay.
Could you perhaps make a reproducable problem starting out from the related example in the 
popmon_tutorial_incremental_data.ipynb notebook?

Normally, the code should automatically derive the next time_bin_idx value where to insert any new batches, no 
need to provide it yourself. It does so based on the histograms found in the hists_basis dictionary. It scans for the max value found on the time_axis of any of those histograms.

I assume you don't see any output like: "Maximum time bin index found: 0"
If not, that can only be when the histograms in the object hists_basis do not all have the same type.
Could you show the contents of the object hists_2 ?

**Comment by jeaninejuliettes** [comment]
Hi @mbaak,

I'm actually getting: Maximum time bin index found: 1
I also managed to reproduce the error. I've attached a very small example notebook which generates the same error using the example data from popmon and the notebook you pointed me at, but with some alterations. The reason why I want to stitch one batch at a time is that I want to repeat that part of the script every time a new batch of data arrives. Since we won't have access to the entire history of data but only to the previously created popmon objects of these datasets and to the new batch of data. 
I hope this makes sense to you. 

Thanks again
[popmon_tutorial_incremental_data.zip](https://github.com/ing-bank/popmon/files/7257050/popmon_tutorial_incremental_data.zip)
!

**Comment by mbaak** [comment]
I understand what you intend to do.

I can't reproduce the problem on my mac but from that I can deduce what the problem must be.
Namely the isinstance check here, which checks for int64:
https://github.com/ing-bank/popmon/blob/master/popmon/stitching/hist_stitcher.py#L313
Your windows machine must be returning a different numpy integer type (int32 probably). 

I've switched np.int64 to np.integer and made a PR:
https://github.com/ing-bank/popmon/pull/144

I assume that will fix the issue. Perhaps you can out the fix locally?

**Comment by sbrugman** [comment]
@jeaninejuliettes The latest version of popmon is released (v0.4.3) with the fix Max provided. Upgrading should resolve it. If not, then please let us know and we'll provide further support. Feel free to open any issues if you run into any other problem or have suggestions for improvement 🚀

**Comment by jeaninejuliettes** [comment]
@mbaak and @sbrugman, sorry for the delay in my response, I've been away for a couple of days. Thank you very much for this quick fix in the newest release. I'm going to try it and will let you know if I still run into issues. Thanks!

**Comment by jeaninejuliettes** [comment]
Works like a charm! I did find another small error in my own code, but after solving that, everything works like I hoped it would. Thanks again!
