### ISSUE TITLE
DataProfiler - A Scalable Data Profiling Library

### ISSUE THREAD

**Issue by lettergram** [ing-bank/popmon#181]
Howdy!

I'm reaching out as a maintainer of the [DataProfiler library](https://github.com/capitalone/dataprofiler).

I think it might be useful to your project so I'm reaching out! Would love to collaborate and see how we can help popmon.

We effectively wrote a library to improve upon the objectives of pandas-profiling with some neat added functionality:

- Auto-Detect & Load: CSV, AVRO, Parquet, JSON, Text, URL data = Data("your_filepath_or_url.csv")
- Profile data: calculating statistics and doing entity detection (for PII) profile = Profiler(data)
- Merge profiles: profile3 = profile1 + profile2; enabling distributed profile generation
- Compare profiles: profile_diff = profile1.diff(profile2)
- Generate reports: readable_report = profile.report(report_options={"output_format": "compact"})

```python
import json
from dataprofiler import Data, Profiler

data = Data("your_file.csv") # Auto-Detect & Load: CSV, AVRO, Parquet, JSON, Text, URL

print(data.data.head(5)) # Access data directly via a compatible Pandas DataFrame

profile = Profiler(data) # Calculate Statistics, Entity Recognition, etc

readable_report = profile.report(report_options={"output_format": "compact"})

print(json.dumps(readable_report, indent=4))
```

**Comment by sbrugman** [comment]
Hi @lettergram , thanks for reaching out. We've been in contact before, happy to discuss. Feel free to set something up.

**Comment by lettergram** [comment]
@sbrugman Ah yes! Totally slipped my mind these two projects are related; seems like we're also moving in the same space here haha. I reached out, if we could connect over email that'd be great.

**Comment by sbrugman** [comment]
We had a chat at the time and DataProfiler appears to be a cool tool. Closing the issue as there is no concrete follow-up atm.
