### ISSUE TITLE
Display histograms over time for EDA

### ISSUE THREAD

**Issue by sbrugman** [ing-bank/popmon#185]
When using popmon for exploratory data analysis of datasets with a time component it would be useful to inspect how variables change over time directly in the histograms.

The simplest example: for categorical variables with low cardinality we could show a table with counts.

Related to https://github.com/ing-bank/popmon/pull/122

**Comment by pradyot-09** [comment]
I would like to work on this issue. I will start with focusing on categorical features with a heat-map approach.

**Comment by sbrugman** [comment]
Perfect @pradyot-09! I'll assign you to the issue!
