### ISSUE TITLE
Ensure date/datetime representation in plots for Spark when providing Timestamp

### ISSUE THREAD

**Issue by sbrugman** [ing-bank/popmon#233]
When the user provides a timestamp-typed time_axis in PySpark, the time axis is binned in (nano)seconds. This should be displayed in as datetimes in the plots.

**Comment by pradyot-09** [comment]
After a lot of debugging, I found that there is a bug in histogrammar with Spark DataFrames. The histogrammar converts timestamps in nanoseconds for binning calculations. However, it fails to convert it back to timestamp for Spark DataFrames. It is a bit more explained in the issue [here](https://github.com/histogrammar/histogrammar-python/issues/58). I have fixed the issue in histogrammar repo and submitted a PR.
