### ISSUE TITLE
Error with pydantic when using some custom settings in the report generation

### ISSUE THREAD

**Issue by gus-morales** [ing-bank/popmon#239]
With version 1.0.0, when using custom settings in `df.pm_stability_report()` like `show_stats`, I get an error stating such option is not allowed:

`ValidationError: 2 validation errors for Settings`

I couldn't reproduce it when using `popmon==0.9.0`.

**Comment by mbaak** [comment]
Thanks for reporting! Will try to reproduce this.

**Comment by sbrugman** [comment]
@gus-morales The syntax for configuration has changed (the version increase indicates a breaking change). Are you using the new syntax? The validation errors should actually be a feature, not a bug.

The [docs](https://popmon.readthedocs.io/en/latest/configuration.html#monitoring-rules) provide examples of how to configure ``popmon``. The full range of options can be found in the [``config.py``](https://github.com/ing-bank/popmon/blob/master/popmon/config.py).

**Comment by sbrugman** [comment]
In order to clarify this in the future we have updated the documentation:
https://popmon.readthedocs.io/en/latest/popmon.html#module-popmon.config
