### ISSUE TITLE
Example screenshots for easier value demonstration to people

### ISSUE THREAD

**Issue by hashhar** [ing-bank/popmon#24]
It might be a good idea to have small screenshots from at least the Profile, Histograms and Traffic Lights reports.

Turns out that Pomon covers a lot of surface area (data profiling, alerting, anomaly detection, incremental data stability/comparision) and supports both pandas and Spark but unfortunately the README as it currently stands looks more targeted to data scientists while the tool looks useful for tracking the data coming from backend systems or being ingested from external sources.

**Comment by tomcis** [comment]
Thank you very much for the notice. Indeed, some of the current contributors have observed this as well and this task is now added (with a high-priority label) to our to-do list. `popmon` is useful for both data scientists (e.g. exploratory analysis) and engineers (e.g. data stability/consistency) and we will be trying to communicate that as clearly as possible.

**Comment by tomcis** [comment]
We have worked on improving the documentation and presentation of the package in the last releases, as well as, added more visual content explaining the purpose of the package (more things in the pipeline). Let's consider this issue closed for now. 

Please let us know if you have any other suggestions on how to improve the understandability of the package's purpose for the broader audience.
