### ISSUE TITLE
Error: cannot import name 'Report' from 'popmon.config'

### ISSUE THREAD

**Issue by lcheng61** [ing-bank/popmon#240]
Code:

import popmon
from popmon import resources
from popmon.config import Report

Got error:
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_707/1841834346.py in <module>
      3 import popmon
      4 from popmon import resources
----> 5 from popmon.config import Report, Setting

ImportError: cannot import name 'Report' from 'popmon.config' (/home/user/.local/lib/python3.7/site-packages/popmon/config.py)

**Comment by sbrugman** [comment]
@lcheng61 What version of ``popmon`` are you running (run `pip freeze | grep popmon`). It should be >= 1.0.0 for this syntax to work

**Comment by lcheng61** [comment]
Got the same error after upgrading to popmon==1.0.0

**Comment by sbrugman** [comment]
@lcheng61 You seem to be using popmon in a notebook. Please make sure you update the package on the right kernel, and restart the notebook. The error should not show up anymore after these steps.

This resource is helpful: https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/#How-to-use-Pip-from-the-Jupyter-Notebook
