### ISSUE TITLE
add license header to all source files

### ISSUE THREAD

**Issue by bolkedebruin** [ing-bank/popmon#25]
It's good practice to use a license header in all files (not per project) to ensure that it's clear what is covered by which license. 

The ci/cd pipeline can be used to check for these headers.

**Comment by tomcis** [comment]
Thank you for suggesting this. We will be adding this to our upcoming release.

**Comment by mgorsk1** [comment]
Another way of going about it could be introducing pre-commit framework with license presence validation like here https://github.com/apache/airflow/blob/master/.pre-commit-config.yaml
