### ISSUE TITLE
missing tutorial datasets

### ISSUE THREAD

**Issue by AlexKoutsman** [ing-bank/popmon#51]
Hi,
awesome tool!

Advanced tutorial datasets are not in test_data dir, but still in notebooks dir, as far as I can see. Hence the advanced tutorial notebooks don't run out of the box, at least for me.
I don't have permissions to push to a develop branch.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	renamed:    popmon/notebooks/flight_delays.csv.gz -> popmon/test_data/flight_delays.csv.gz
	renamed:    popmon/notebooks/flight_delays_reference.csv.gz -> popmon/test_data/flight_delays_reference.csv.gz

Cheers - Alex

**Comment by tomcis** [comment]
Hi Alex! 

Great catch. Could you please create a separate feature branch + pull request to `develop` instead of pushing directly to `develop`? That should work.

**Comment by AlexKoutsman** [comment]
Hi Tomas,

I tried to make a new feature branch and push it, but I still dont have the permissions. 🙁

>git push -u origin tutorial_datasets
Warning: Permanently added the RSA host key for IP address '140.82.118.3' to the list of known hosts.
ERROR: Permission to ing-bank/popmon.git denied to AlexKoutsman.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Can you check whether externals are allowed to make feature branches?

Cheers -Alex
________________________________
Van: Tomas Sostak <notifications@github.com>
Verzonden: donderdag 9 juli 2020 18:44
Aan: ing-bank/popmon <popmon@noreply.github.com>
CC: Koutsman, AJ (Alex) <Alex.Koutsman@eneco.com>; Author <author@noreply.github.com>
Onderwerp: Re: [ing-bank/popmon] missing tutorial datasets (#51)


Hi Alex!

Great catch. Could you please create a separate feature branch + pull request to develop instead of pushing directly to develop? That should work.

**Comment by tomcis** [comment]
Hi Alex,

Sorry for the confusion: please try to create a fork first, push it there and create a pull request from your fork into `develop`.

Cheers
