### ISSUE TITLE
Library doesn't run in Spark 3.0+: Replace the dependency of histogrammar with native Spark functionality

### ISSUE THREAD

**Issue by kedemdor** [ing-bank/popmon#77]
Currently, the dependency with the library, which hasn't been further developed since 2016, creates a dependency with Scala 2.11 which limits the execution in Spark 3.0 (which was only built on Scala 2.12). I think I could replace the functionality with Bucketizer functionality in native spark.

**Comment by mbaak** [comment]
The histogrammar dependency is not ideal, but we've not seen a good alternative yet. Something that works for both pandas and spark. (Filling histograms is not very hard, but doing it well and being complete is. There are a lot of small details to get right.) I have access to histogrammar, let me try to make an upgrade of the jar file. 
(Btw we can also discuss in the popmon channel.)

**Comment by mbaak** [comment]
Hi Dor, if you set the histogrammar jar file to “io.github.histogrammar:histogrammar-sparksql_2.12:1.0.11" then popmon should work again with spark 3.0. Can you give it a try? (It works for me.) I will update the popmon examples tomorrow.

**Comment by mbaak** [comment]
Several people tried, it's working okay now. Closing the issue.
