### ISSUE TITLE
PyPI sdist failure

### ISSUE THREAD

**Issue by jayvdb** [ing-bank/popmon#85]
The file requirements.txt isnt included in the PyPI sdist, resulting in

```py
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    with open("requirements.txt") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by tomcis** [comment]
Thanks for the ticket. The issue should be resolved in the next package release #88 (merged into `develop`)
